version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

  settings:
    errcheck:
      check-blank: true
      exclude-functions:
        # Common functions where ignoring errors is acceptable in tests
        - os.Setenv
        - os.Unsetenv
        - os.RemoveAll

formatters:
  enable:
    - gofmt
