version: 2
project_name: rr

builds:
  - main: ./cmd/rr
    binary: rr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

homebrew_casks:
  - name: rr
    binaries:
      - rr
    homepage: https://github.com/rileyhilliard/rr
    description: Sync code and run commands on remote machines
    url:
      verified: github.com/rileyhilliard/rr/
    repository:
      owner: rileyhilliard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rr"]
          end
