version: 2
project_name: rr

builds:
  - main: ./cmd/rr
    binary: rr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: rileyhilliard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/rileyhilliard/rr
    description: Sync code and run commands on remote machines
    license: MIT
    install: |
      bin.install "rr"
      bash_completion.install "completions/rr.bash" => "rr"
      zsh_completion.install "completions/_rr"
      fish_completion.install "completions/rr.fish"
    test: |
      system "#{bin}/rr", "--version"
